language: cpp
os: linux
compiler: gcc
dist: trusty

addons:
  apt:
    # Get new gcc
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
    # Add repository for Qt
    - sudo apt-add-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
    - sudo apt-get -qq update
    # Decrypt auth token for deployment
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_32e4a7602a6c_key -iv $encrypted_32e4a7602a6c_iv -in deployment/.dropbox_uploader.enc -out ~/.dropbox_uploader -d'

install:
    # Install needed Qt modules
    - sudo apt-get --yes install qt510base qt510svg qt510script qt510declarative
    
    # Set Qt variables
    - QTDIR="/opt/qt510"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt510/bin/qt510-env.sh
    
    # Set used gcc version
    - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - export CC=gcc-7
    - export CXX=g++-7

script:
    # Build atools
    - mkdir ../build-atools-release
    - cd ../build-atools-release
    - qmake ../atools/atools.pro CONFIG+=release
    - make

after_success:
    # Deploy artefacts to dropbox
    - '[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh delete build-atools-release'
    - '[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh mkdir build-atools-release'
    - '[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh upload ../build-atools-release build-atools-release'
